### ISSUE TITLE
Modificaciones de archivos independientes

### ISSUE THREAD

**Issue by 2314-RAustin** [theLastPixel/LogIn#10]
Es necesario estos cambios debido a que a veces se requiere modificar la altura de cada interfaz, al igual que se modifica la altura las posiciones por defecto del Header y del Footer cambian y estos se pueden ver afectados.

Height del grit-toal
Row y column del Header
Row y column del Footer

**Comment by 2314-RAustin** [comment]
- [ ] Height del grit-toal

- [ ] Row y column del Header

- [ ] Row y column del Footer

**Comment by JCrespo25** [comment]
Ya se acomodo el header y el footer.
