### ISSUE TITLE
Reorganización de la ventana sign

### ISSUE THREAD

**Issue by 2314-RAustin** [theLastPixel/LogIn#21]
-Header
1. Modificar el icono de microsoft
2. Darle estilo al combobox del idioma

-Sign In
1. Cambiar Sign In por Iniciar sesion
2. Cambiar placeholder de User por Usuario
3. Cambiar Placeholder de Password por contraseña
4. Cambiar el value del boton Log In por entrar
5. Cambiar el fondo

-Sign Up
1. Reestructurar las posiciones de los elementos
2. Agregar labels a cada boton con su respectivo nombre
3. Agregar * al final de cada label que es requerido
4. Cambiar los placeholder por ejemplo:.......

-Footer
1. Reestructurar y rediseñar completamente el footer por algo sencillo

**Comment by 2314-RAustin** [comment]
-Header
- [ ] Modificar el icono de microsoft
- [ ] Darle estilo al combobox del idioma

-Sign In
- [ ] Cambiar Sign In por Iniciar sesion
- [ ] Cambiar placeholder de User por Usuario
- [ ] Cambiar Placeholder de Password por contraseña
- [ ] Cambiar el value del boton Log In por entrar
- [ ] Cambiar el fondo

-Sign Up
- [ ] Reestructurar las posiciones de los elementos
- [ ] Agregar labels a cada boton con su respectivo nombre
- [ ]     Agregar * al final de cada label que es requerido
- [ ]     Cambiar los placeholder por ejemplo:....

-Footer
- [ ]     Reestructurar y rediseñar completamente el footer por algo sencillo

**Comment by JCrespo25** [comment]
Listo se cumplieron con cada una de las tareas asignadas.
