### ISSUE TITLE
Modal solicitudes

### ISSUE THREAD

**Issue by 2314-RAustin** [theLastPixel/LogIn#23]
General:
Agregar opcion de regresar:

Paso 1:
1. Reestructurar posiciones del los elementos
2. Cambiarlos a español
3. Agregar campo de Usuario
4. Agregar campo de contraseña
5. Agregar campo de Confirmar contraseña
6. Agregar pregunta de seguridad
7. Agregar campo de respuesta de pregunta de seguridad

Paso: 2:
1. Cambiar titulo de Facturación a Datos fiscales
2. Agregar icono de mexico
3. Estructurar los datos de facturacion mexicana
4. Agregar icono de E.U.A
5. Estructurar los datos de facturacion americana
6. Quitar boton Restablecer

Paso: 3
1. Cambiar titulo privilegios por Modulos
2. Agregar mas opciones de modulos
3. Cambiar nombres de options por nombres reales
4. Titulo de privilegios de modulos por Demo
5. Agregar titulo otros modulos
6. Listar mas checkbox en otros modulos
7. Terminar y guardar en el paso 3

Paso: 4
1. Eliminar el paso 4

**Comment by 2314-RAustin** [comment]
Paso 1:
- [ ]     Reestructurar posiciones del los elementos
- [ ]     Cambiarlos a español
- [ ]     Agregar campo de Usuario
- [ ]     Agregar campo de contraseña
- [ ]     Agregar campo de Confirmar contraseña
- [ ]     Agregar pregunta de seguridad
- [ ]     Agregar campo de respuesta de pregunta de seguridad

Paso: 2:
- [ ]     Cambiar titulo de Facturación a Datos fiscales
- [ ]     Agregar icono de mexico
- [ ]     Estructurar los datos de facturacion mexicana
- [ ]     Agregar icono de E.U.A
- [ ]     Estructurar los datos de facturacion americana
- [ ]     Quitar boton Restablecer

Paso: 3
- [ ]     Cambiar titulo privilegios por Modulos
- [ ]     Agregar mas opciones de modulos
- [ ]     Cambiar nombres de options por nombres reales
- [ ]     Titulo de privilegios de modulos por Demo
- [ ]     Agregar titulo otros modulos
- [ ]     Listar mas checkbox en otros modulos
- [ ]     Terminar y guardar en el paso 3

Paso: 4
- [ ]     Eliminar el paso 4

**Comment by JCrespo25** [comment]
Se realizaron algunos cambios con éxito.

**Comment by JCrespo25** [comment]
Se terminaron las tareas pendientes por el momento, hay una donde todavía esta en etapa de análisis.
