### ISSUE TITLE
Lista tareas

### ISSUE THREAD

**Issue by 2314-RAustin** [theLastPixel/LogIn#31]
1. Agregar borradores (Master/Cliente)
2. Interfaz (Cliente)
3. Modificación menú (Master)
4. Catalogo (Cliente)
  4.1 Emplados x conductores (Cliente)
  4.2 Unidad x Unidades (Cliente)
5. Logistica x Despacho (Cliente)
6. Imventario x Almacen (Cliente)
7. Modificar GRID de alta_Empleados (Master)
8. Pull Request
9. Inicio * Dashboard (Master/Cliente)

**Comment by 2314-RAustin** [comment]
- [ ] Agregar borradores (Master/Cliente)
- [ ] Interfaz (Cliente)
- [ ] Modificación menú (Master)
 Catalogo (Cliente)
- [ ] Emplados x conductores (Cliente)
- [ ] Unidad x Unidades (Cliente)
- [ ] Logistica x Despacho (Cliente)
- [ ] Imventario x Almacen (Cliente)
- [ ] Modificar GRID de alta_Empleados (Master)
- [ ] Pull Request
- [ ] Inicio * Dashboard (Master/Cliente)

**Comment by JCrespo25** [comment]
Se han realizado todas las tareas correspondientes.
